`timescale 1ns/1ps
//-----------------------------------------------------------------------------
// Wrapper for the split-CDAC SAR controller + reconstruction.
// GENERATED by gen_wrapper.py (scalar ports so the SPICE / XSPICE pin names
// equal the analog net names of xschem/sar_10_bit_split_cal.sch).
//
// Analog controls : sample rstf comp_clk  bp9..bp5 bpr bp4..bp0  bn9..bn5 bnr bn4..bn0
// Handshake       : start (level, see sar_split_cal_fsm.v) busy valid
// Digital code    : code9..code0 (valid-qualified), sat
// Debug / cal     : raw11..raw0 (raw11 = first comparison), raw_stb,
//                   cal_en cal_we cal_addr3..0 cal_wdata17..0
// All signals are 3.3 V (gf180mcu_fd_sc_mcu7t5v0 at 3.3 V; analog switches,
// comparator and controller share one VDD domain -> no level shifters).
//-----------------------------------------------------------------------------
module sar_split_cal_wrapper #(
    parameter integer SAMPLE_CYCLES = 26,
    parameter integer RST_LEAD      = 1,
    parameter integer SETTLE_CYCLES = 1,
    parameter integer EVAL_CYCLES   = 1,
    parameter         INVERT_COMP   = 1'b0
)(
    input  wire clk,
    input  wire rst_n,
    input  wire start,
    input  wire comp,
    input  wire cal_en,
    input  wire cal_we,
    input  wire cal_addr3,
    input  wire cal_addr2,
    input  wire cal_addr1,
    input  wire cal_addr0,
    input  wire cal_wdata17,
    input  wire cal_wdata16,
    input  wire cal_wdata15,
    input  wire cal_wdata14,
    input  wire cal_wdata13,
    input  wire cal_wdata12,
    input  wire cal_wdata11,
    input  wire cal_wdata10,
    input  wire cal_wdata9,
    input  wire cal_wdata8,
    input  wire cal_wdata7,
    input  wire cal_wdata6,
    input  wire cal_wdata5,
    input  wire cal_wdata4,
    input  wire cal_wdata3,
    input  wire cal_wdata2,
    input  wire cal_wdata1,
    input  wire cal_wdata0,
    output wire sample,
    output wire rstf,
    output wire comp_clk,
    output wire busy,
    output wire valid,
    output wire raw_stb,
    output wire sat,
    output wire bp9,
    output wire bp8,
    output wire bp7,
    output wire bp6,
    output wire bp5,
    output wire bpr,
    output wire bp4,
    output wire bp3,
    output wire bp2,
    output wire bp1,
    output wire bp0,
    output wire bn9,
    output wire bn8,
    output wire bn7,
    output wire bn6,
    output wire bn5,
    output wire bnr,
    output wire bn4,
    output wire bn3,
    output wire bn2,
    output wire bn1,
    output wire bn0,
    output wire code9,
    output wire code8,
    output wire code7,
    output wire code6,
    output wire code5,
    output wire code4,
    output wire code3,
    output wire code2,
    output wire code1,
    output wire code0,
    output wire raw11,
    output wire raw10,
    output wire raw9,
    output wire raw8,
    output wire raw7,
    output wire raw6,
    output wire raw5,
    output wire raw4,
    output wire raw3,
    output wire raw2,
    output wire raw1,
    output wire raw0
);

    wire [10:0] bp, bn;
    wire [11:0] raw, raw_q;
    wire [9:0]  code;
    wire        raw_stb_i;

    sar_split_cal_logic #(
        .NSTEP(11), .SAMPLE_CYCLES(SAMPLE_CYCLES), .RST_LEAD(RST_LEAD),
        .SETTLE_CYCLES(SETTLE_CYCLES), .EVAL_CYCLES(EVAL_CYCLES), .INVERT_COMP(INVERT_COMP)
    ) u_fsm (
        .clk(clk), .rst_n(rst_n), .start(start), .comp(comp),
        .sample(sample), .rstf(rstf), .comp_clk(comp_clk), .busy(busy), .raw_stb(raw_stb_i),
        .bp(bp), .bn(bn), .raw(raw)
    );

    sar_split_cal_recon #(.NCMP(12), .F(6), .CW(16), .AW(18)) u_recon (
        .clk(clk), .rst_n(rst_n), .raw_stb(raw_stb_i), .raw(raw),
        .cal_en(cal_en), .cal_we(cal_we),
        .cal_addr({cal_addr3, cal_addr2, cal_addr1, cal_addr0}),
        .cal_wdata({cal_wdata17, cal_wdata16, cal_wdata15, cal_wdata14, cal_wdata13, cal_wdata12, cal_wdata11, cal_wdata10, cal_wdata9, cal_wdata8, cal_wdata7, cal_wdata6, cal_wdata5, cal_wdata4, cal_wdata3, cal_wdata2, cal_wdata1, cal_wdata0}),
        .code(code), .raw_q(raw_q), .sat(sat), .valid(valid)
    );

    assign raw_stb = raw_stb_i;
    assign bp9 = bp[0];  assign bn9 = bn[0];
    assign bp8 = bp[1];  assign bn8 = bn[1];
    assign bp7 = bp[2];  assign bn7 = bn[2];
    assign bp6 = bp[3];  assign bn6 = bn[3];
    assign bp5 = bp[4];  assign bn5 = bn[4];
    assign bpr = bp[5];  assign bnr = bn[5];
    assign bp4 = bp[6];  assign bn4 = bn[6];
    assign bp3 = bp[7];  assign bn3 = bn[7];
    assign bp2 = bp[8];  assign bn2 = bn[8];
    assign bp1 = bp[9];  assign bn1 = bn[9];
    assign bp0 = bp[10];  assign bn0 = bn[10];
    assign code0 = code[0];
    assign code1 = code[1];
    assign code2 = code[2];
    assign code3 = code[3];
    assign code4 = code[4];
    assign code5 = code[5];
    assign code6 = code[6];
    assign code7 = code[7];
    assign code8 = code[8];
    assign code9 = code[9];
    assign raw0 = raw_q[0];
    assign raw1 = raw_q[1];
    assign raw2 = raw_q[2];
    assign raw3 = raw_q[3];
    assign raw4 = raw_q[4];
    assign raw5 = raw_q[5];
    assign raw6 = raw_q[6];
    assign raw7 = raw_q[7];
    assign raw8 = raw_q[8];
    assign raw9 = raw_q[9];
    assign raw10 = raw_q[10];
    assign raw11 = raw_q[11];

endmodule
