/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module \$paramod\sar_logic\N=10\SAMPLE_CYCLES=4\DAC_SETTLE_CYCLES=3\INVERT_COMP=1'0 (clk, rst_n, start, comp, sample, comp_clk, busy, valid, bp, bn, code);
  wire [3:0] _000_;
  wire [9:0] _001_;
  wire [9:0] _002_;
  wire _003_;
  wire [9:0] _004_;
  wire [7:0] _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire [3:0] bit_idx;
  output [9:0] bn;
  output [9:0] bp;
  output busy;
  input clk;
  wire cmp_p_gt_n;
  output [9:0] code;
  input comp;
  output comp_clk;
  wire [7:0] count;
  input rst_n;
  output sample;
  input start;
  wire [5:0] state;
  output valid;
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _142_ (
    .I(bit_idx[1]),
    .ZN(_012_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _143_ (
    .I(bit_idx[2]),
    .ZN(_013_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _144_ (
    .I(comp_clk),
    .ZN(_014_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _145_ (
    .I(state[2]),
    .ZN(_015_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _146_ (
    .I(count[2]),
    .ZN(_016_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _147_ (
    .I(count[3]),
    .ZN(_017_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _148_ (
    .I(count[4]),
    .ZN(_018_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _149_ (
    .I(count[5]),
    .ZN(_019_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _150_ (
    .I(count[6]),
    .ZN(_020_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _151_ (
    .I(bit_idx[3]),
    .ZN(_021_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _152_ (
    .I(bit_idx[0]),
    .ZN(_022_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _153_ (
    .I(code[1]),
    .ZN(_023_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _154_ (
    .I(code[2]),
    .ZN(_024_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _155_ (
    .I(start),
    .ZN(_025_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _156_ (
    .I(code[0]),
    .ZN(_026_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _157_ (
    .I(count[1]),
    .ZN(_027_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _158_ (
    .I(bp[9]),
    .ZN(_028_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _159_ (
    .I(bp[8]),
    .ZN(_029_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _160_ (
    .I(bp[0]),
    .ZN(_030_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _161_ (
    .I(bn[8]),
    .ZN(_031_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _162_ (
    .I(bn[6]),
    .ZN(_032_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _163_ (
    .I(bn[5]),
    .ZN(_033_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _164_ (
    .I(bn[4]),
    .ZN(_034_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _165_ (
    .I(bn[3]),
    .ZN(_035_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _166_ (
    .I(bn[2]),
    .ZN(_036_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _167_ (
    .I(bn[1]),
    .ZN(_037_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _168_ (
    .I(bn[0]),
    .ZN(_038_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _169_ (
    .I(code[7]),
    .ZN(_039_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _170_ (
    .I(code[6]),
    .ZN(_040_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _171_ (
    .I(code[5]),
    .ZN(_041_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _172_ (
    .I(code[4]),
    .ZN(_042_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _173_ (
    .I(code[3]),
    .ZN(_043_)
  );
  gf180mcu_fd_sc_mcu7t5v0__clkinv_1 _174_ (
    .I(busy),
    .ZN(_044_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _175_ (
    .A1(count[2]),
    .A2(count[3]),
    .Z(_045_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _176_ (
    .A1(count[4]),
    .A2(count[5]),
    .A3(count[6]),
    .A4(count[7]),
    .Z(_046_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or4_1 _177_ (
    .A1(count[0]),
    .A2(_027_),
    .A3(_045_),
    .A4(_046_),
    .Z(_047_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _178_ (
    .A1(state[2]),
    .A2(_047_),
    .ZN(_048_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _179_ (
    .A1(count[0]),
    .A2(count[1]),
    .ZN(_049_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _180_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_049_),
    .ZN(_050_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _181_ (
    .A1(state[3]),
    .A2(_050_),
    .ZN(_051_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _182_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[0]),
    .ZN(_052_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _183_ (
    .A1(bit_idx[2]),
    .A2(bit_idx[3]),
    .ZN(_053_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _184_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[2]),
    .A3(bit_idx[0]),
    .ZN(_054_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _185_ (
    .A1(_021_),
    .A2(_054_),
    .ZN(_055_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _186_ (
    .A1(comp_clk),
    .A2(_055_),
    .ZN(_056_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _187_ (
    .A1(_048_),
    .A2(_051_),
    .A3(_056_),
    .ZN(_010_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _188_ (
    .A1(state[0]),
    .A2(start),
    .ZN(_057_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _189_ (
    .A1(_045_),
    .A2(_046_),
    .A3(_049_),
    .B(state[3]),
    .ZN(_058_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _190_ (
    .A1(_057_),
    .A2(_058_),
    .ZN(_011_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _191_ (
    .A1(state[0]),
    .A2(_025_),
    .Z(_059_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _192_ (
    .A1(state[4]),
    .A2(_059_),
    .Z(_009_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _193_ (
    .A1(state[0]),
    .A2(state[3]),
    .ZN(_060_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _194_ (
    .A1(comp_clk),
    .A2(_059_),
    .A3(_060_),
    .ZN(_061_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _195_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[2]),
    .A3(_021_),
    .A4(_022_),
    .ZN(_062_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _196_ (
    .A1(_012_),
    .A2(_013_),
    .A3(bit_idx[3]),
    .A4(bit_idx[0]),
    .ZN(_063_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _197_ (
    .A1(_014_),
    .A2(comp),
    .A3(_063_),
    .B1(_061_),
    .B2(_028_),
    .ZN(_002_[9])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _198_ (
    .A1(comp_clk),
    .A2(bit_idx[3]),
    .A3(_054_),
    .ZN(_064_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _199_ (
    .A1(comp),
    .A2(_064_),
    .Z(_065_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _200_ (
    .A1(_029_),
    .A2(_065_),
    .B(_061_),
    .ZN(_002_[8])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _201_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[0]),
    .ZN(_066_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _202_ (
    .A1(_013_),
    .A2(bit_idx[3]),
    .A3(_066_),
    .ZN(_067_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _203_ (
    .A1(_014_),
    .A2(comp),
    .ZN(_068_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _204_ (
    .A1(_067_),
    .A2(_068_),
    .B(bp[7]),
    .ZN(_069_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _205_ (
    .A1(_061_),
    .A2(_069_),
    .ZN(_002_[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _206_ (
    .A1(_012_),
    .A2(_013_),
    .A3(bit_idx[3]),
    .A4(bit_idx[0]),
    .ZN(_070_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _207_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[2]),
    .A3(_021_),
    .A4(_022_),
    .ZN(_071_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _208_ (
    .A1(_068_),
    .A2(_070_),
    .B(bp[6]),
    .ZN(_072_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _209_ (
    .A1(_061_),
    .A2(_072_),
    .ZN(_002_[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor4_1 _210_ (
    .A1(bit_idx[1]),
    .A2(_013_),
    .A3(bit_idx[3]),
    .A4(_022_),
    .ZN(_073_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand4_1 _211_ (
    .A1(_012_),
    .A2(bit_idx[2]),
    .A3(_021_),
    .A4(bit_idx[0]),
    .ZN(_074_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _212_ (
    .A1(_068_),
    .A2(_073_),
    .B(bp[5]),
    .ZN(_075_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _213_ (
    .A1(_061_),
    .A2(_075_),
    .ZN(_002_[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _214_ (
    .A1(bit_idx[2]),
    .A2(_021_),
    .A3(_052_),
    .Z(_076_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _215_ (
    .A1(bit_idx[2]),
    .A2(_021_),
    .A3(_052_),
    .ZN(_077_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _216_ (
    .A1(_068_),
    .A2(_076_),
    .B(bp[4]),
    .ZN(_078_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _217_ (
    .A1(_061_),
    .A2(_078_),
    .ZN(_002_[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _218_ (
    .A1(bit_idx[2]),
    .A2(bit_idx[3]),
    .A3(_066_),
    .ZN(_079_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _219_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[0]),
    .A3(_053_),
    .ZN(_080_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _220_ (
    .A1(_068_),
    .A2(_079_),
    .B(bp[3]),
    .ZN(_081_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _221_ (
    .A1(_061_),
    .A2(_081_),
    .ZN(_002_[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _222_ (
    .A1(bit_idx[1]),
    .A2(_022_),
    .A3(_053_),
    .Z(_082_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _223_ (
    .A1(bit_idx[1]),
    .A2(_022_),
    .A3(_053_),
    .ZN(_083_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _224_ (
    .A1(_068_),
    .A2(_082_),
    .B(bp[2]),
    .ZN(_084_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _225_ (
    .A1(_061_),
    .A2(_084_),
    .ZN(_002_[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _226_ (
    .A1(_012_),
    .A2(bit_idx[0]),
    .A3(_053_),
    .Z(_085_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _227_ (
    .A1(_012_),
    .A2(bit_idx[0]),
    .A3(_053_),
    .ZN(_086_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _228_ (
    .A1(_068_),
    .A2(_085_),
    .B(bp[1]),
    .ZN(_087_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _229_ (
    .A1(_061_),
    .A2(_087_),
    .ZN(_002_[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _230_ (
    .A1(_030_),
    .A2(_061_),
    .ZN(_002_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _231_ (
    .A1(comp_clk),
    .A2(comp),
    .Z(_088_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _232_ (
    .A1(bit_idx[3]),
    .A2(_054_),
    .A3(_088_),
    .ZN(_089_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _233_ (
    .A1(_031_),
    .A2(_089_),
    .B(_061_),
    .ZN(_001_[8])
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _234_ (
    .A1(_067_),
    .A2(_088_),
    .Z(_090_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _235_ (
    .A1(_067_),
    .A2(_088_),
    .B(bn[7]),
    .ZN(_091_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _236_ (
    .A1(_061_),
    .A2(_091_),
    .ZN(_001_[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _237_ (
    .A1(_070_),
    .A2(_088_),
    .ZN(_092_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _238_ (
    .A1(_032_),
    .A2(_092_),
    .B(_061_),
    .ZN(_001_[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _239_ (
    .A1(_073_),
    .A2(_088_),
    .ZN(_093_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _240_ (
    .A1(_033_),
    .A2(_093_),
    .B(_061_),
    .ZN(_001_[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _241_ (
    .A1(_076_),
    .A2(_088_),
    .ZN(_094_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _242_ (
    .A1(_034_),
    .A2(_094_),
    .B(_061_),
    .ZN(_001_[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _243_ (
    .A1(_079_),
    .A2(_088_),
    .ZN(_095_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _244_ (
    .A1(_035_),
    .A2(_095_),
    .B(_061_),
    .ZN(_001_[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _245_ (
    .A1(_082_),
    .A2(_088_),
    .ZN(_096_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _246_ (
    .A1(_036_),
    .A2(_096_),
    .B(_061_),
    .ZN(_001_[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _247_ (
    .A1(_085_),
    .A2(_088_),
    .ZN(_097_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _248_ (
    .A1(_037_),
    .A2(_097_),
    .B(_061_),
    .ZN(_001_[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _249_ (
    .A1(_038_),
    .A2(_061_),
    .ZN(_001_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _250_ (
    .A1(bit_idx[3]),
    .A2(_054_),
    .B(_014_),
    .ZN(_098_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _251_ (
    .A1(state[0]),
    .A2(_014_),
    .ZN(_099_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _252_ (
    .A1(state[0]),
    .A2(comp_clk),
    .ZN(_100_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _253_ (
    .I0(_014_),
    .I1(_025_),
    .S(state[0]),
    .Z(_101_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _254_ (
    .A1(state[0]),
    .A2(_014_),
    .B(_057_),
    .ZN(_102_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _255_ (
    .A1(_098_),
    .A2(_101_),
    .B(code[8]),
    .ZN(_103_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _256_ (
    .A1(_089_),
    .A2(_103_),
    .ZN(_004_[8])
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _257_ (
    .A1(_013_),
    .A2(bit_idx[3]),
    .A3(_066_),
    .B(comp_clk),
    .ZN(_104_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _258_ (
    .A1(_102_),
    .A2(_104_),
    .B(_039_),
    .ZN(_105_)
  );
  gf180mcu_fd_sc_mcu7t5v0__or2_1 _259_ (
    .A1(_090_),
    .A2(_105_),
    .Z(_004_[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _260_ (
    .A1(comp_clk),
    .A2(_071_),
    .B(_101_),
    .ZN(_106_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _261_ (
    .A1(_040_),
    .A2(_106_),
    .B(_092_),
    .ZN(_004_[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _262_ (
    .A1(comp_clk),
    .A2(_074_),
    .B(_101_),
    .ZN(_107_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _263_ (
    .A1(_041_),
    .A2(_107_),
    .B(_093_),
    .ZN(_004_[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _264_ (
    .A1(comp_clk),
    .A2(_077_),
    .B(_101_),
    .ZN(_108_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _265_ (
    .A1(_042_),
    .A2(_108_),
    .B(_094_),
    .ZN(_004_[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _266_ (
    .A1(comp_clk),
    .A2(_080_),
    .B(_101_),
    .ZN(_109_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _267_ (
    .A1(_043_),
    .A2(_109_),
    .B(_095_),
    .ZN(_004_[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _268_ (
    .A1(comp_clk),
    .A2(_083_),
    .B(_101_),
    .ZN(_110_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _269_ (
    .A1(_024_),
    .A2(_110_),
    .B(_096_),
    .ZN(_004_[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _270_ (
    .A1(comp_clk),
    .A2(_086_),
    .B(_101_),
    .ZN(_111_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _271_ (
    .A1(_023_),
    .A2(_111_),
    .B(_097_),
    .ZN(_004_[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _272_ (
    .A1(comp_clk),
    .A2(_055_),
    .B(_101_),
    .ZN(_112_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and3_1 _273_ (
    .A1(comp_clk),
    .A2(_021_),
    .A3(_054_),
    .Z(_007_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _274_ (
    .A1(comp),
    .A2(_007_),
    .ZN(_113_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _275_ (
    .A1(_026_),
    .A2(_112_),
    .B(_113_),
    .ZN(_004_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _276_ (
    .A1(state[0]),
    .A2(start),
    .B(bit_idx[0]),
    .ZN(_114_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _277_ (
    .A1(bit_idx[0]),
    .A2(_099_),
    .B1(_114_),
    .B2(_056_),
    .ZN(_000_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _278_ (
    .A1(bit_idx[1]),
    .A2(bit_idx[0]),
    .Z(_115_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _279_ (
    .A1(_012_),
    .A2(_102_),
    .B1(_115_),
    .B2(_056_),
    .ZN(_000_[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _280_ (
    .A1(_014_),
    .A2(_052_),
    .ZN(_116_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _281_ (
    .A1(_101_),
    .A2(_116_),
    .B(bit_idx[2]),
    .ZN(_117_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _282_ (
    .A1(_064_),
    .A2(_117_),
    .ZN(_000_[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _283_ (
    .A1(_021_),
    .A2(_057_),
    .B1(_099_),
    .B2(_054_),
    .ZN(_000_[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _284_ (
    .A1(state[2]),
    .A2(_047_),
    .B(state[3]),
    .ZN(_118_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _285_ (
    .A1(state[2]),
    .A2(_047_),
    .B(count[0]),
    .C(state[3]),
    .ZN(_119_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _286_ (
    .A1(state[3]),
    .A2(state[2]),
    .ZN(_120_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi22_1 _287_ (
    .A1(state[0]),
    .A2(_025_),
    .B1(_100_),
    .B2(_120_),
    .ZN(_121_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi211_1 _288_ (
    .A1(_100_),
    .A2(_120_),
    .B(_007_),
    .C(_059_),
    .ZN(_122_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _289_ (
    .A1(count[0]),
    .A2(_122_),
    .B(_119_),
    .ZN(_005_[0])
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _290_ (
    .A1(count[0]),
    .A2(_027_),
    .Z(_123_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _291_ (
    .A1(_027_),
    .A2(_122_),
    .B1(_123_),
    .B2(_118_),
    .ZN(_005_[1])
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _292_ (
    .A1(count[0]),
    .A2(count[1]),
    .B(count[2]),
    .ZN(_124_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _293_ (
    .A1(_015_),
    .A2(_058_),
    .Z(_125_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _294_ (
    .A1(_016_),
    .A2(_049_),
    .ZN(_126_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _295_ (
    .A1(_124_),
    .A2(_125_),
    .A3(_126_),
    .B1(_122_),
    .B2(_016_),
    .ZN(_005_[2])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _296_ (
    .A1(count[3]),
    .A2(_126_),
    .ZN(_127_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _297_ (
    .A1(count[0]),
    .A2(count[2]),
    .A3(count[3]),
    .A4(count[1]),
    .Z(_128_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai32_1 _298_ (
    .A1(_120_),
    .A2(_127_),
    .A3(_128_),
    .B1(_122_),
    .B2(_017_),
    .ZN(_005_[3])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _299_ (
    .A1(count[4]),
    .A2(_128_),
    .ZN(_129_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _300_ (
    .A1(_018_),
    .A2(_128_),
    .Z(_130_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _301_ (
    .A1(_018_),
    .A2(_122_),
    .B1(_130_),
    .B2(_120_),
    .ZN(_005_[4])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand3_1 _302_ (
    .A1(count[4]),
    .A2(count[5]),
    .A3(_128_),
    .ZN(_131_)
  );
  gf180mcu_fd_sc_mcu7t5v0__xor2_1 _303_ (
    .A1(count[5]),
    .A2(_129_),
    .Z(_132_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai22_1 _304_ (
    .A1(_019_),
    .A2(_122_),
    .B1(_132_),
    .B2(_120_),
    .ZN(_005_[5])
  );
  gf180mcu_fd_sc_mcu7t5v0__and4_1 _305_ (
    .A1(count[4]),
    .A2(count[5]),
    .A3(count[6]),
    .A4(_128_),
    .Z(_133_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai221_1 _306_ (
    .A1(_014_),
    .A2(_055_),
    .B1(_120_),
    .B2(_133_),
    .C(_121_),
    .ZN(_134_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _307_ (
    .A1(_120_),
    .A2(_131_),
    .B(_020_),
    .ZN(_135_)
  );
  gf180mcu_fd_sc_mcu7t5v0__and2_1 _308_ (
    .A1(_134_),
    .A2(_135_),
    .Z(_005_[6])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor3_1 _309_ (
    .A1(_020_),
    .A2(_120_),
    .A3(_131_),
    .ZN(_136_)
  );
  gf180mcu_fd_sc_mcu7t5v0__mux2_1 _310_ (
    .I0(_136_),
    .I1(_134_),
    .S(count[7]),
    .Z(_005_[7])
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _311_ (
    .A1(code[9]),
    .A2(_062_),
    .ZN(_137_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _312_ (
    .A1(code[9]),
    .A2(_101_),
    .ZN(_138_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _313_ (
    .A1(comp),
    .A2(_063_),
    .B(comp_clk),
    .ZN(_139_)
  );
  gf180mcu_fd_sc_mcu7t5v0__oai21_1 _314_ (
    .A1(_137_),
    .A2(_139_),
    .B(_138_),
    .ZN(_004_[9])
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _315_ (
    .A1(sample),
    .A2(_060_),
    .ZN(_140_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 _316_ (
    .A1(_058_),
    .A2(_140_),
    .ZN(_006_)
  );
  gf180mcu_fd_sc_mcu7t5v0__aoi21_1 _317_ (
    .A1(_062_),
    .A2(_088_),
    .B(bn[9]),
    .ZN(_141_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _318_ (
    .A1(_061_),
    .A2(_141_),
    .ZN(_001_[9])
  );
  gf180mcu_fd_sc_mcu7t5v0__oai31_1 _319_ (
    .A1(state[4]),
    .A2(state[0]),
    .A3(_044_),
    .B(_057_),
    .ZN(_003_)
  );
  gf180mcu_fd_sc_mcu7t5v0__nor2_1 _320_ (
    .A1(_015_),
    .A2(_047_),
    .ZN(_008_)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _321_ (
    .CLK(clk),
    .D(_009_),
    .Q(state[0]),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _322_ (
    .CLK(clk),
    .D(state[5]),
    .Q(comp_clk),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _323_ (
    .CLK(clk),
    .D(_010_),
    .Q(state[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _324_ (
    .CLK(clk),
    .D(_011_),
    .Q(state[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _325_ (
    .CLK(clk),
    .D(_007_),
    .Q(state[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _326_ (
    .CLK(clk),
    .D(_008_),
    .Q(state[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _327_ (
    .CLK(clk),
    .D(_003_),
    .Q(busy),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _328_ (
    .CLK(clk),
    .D(state[4]),
    .Q(valid),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _329_ (
    .CLK(clk),
    .D(_002_[0]),
    .Q(bp[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _330_ (
    .CLK(clk),
    .D(_002_[1]),
    .Q(bp[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _331_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(bp[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _332_ (
    .CLK(clk),
    .D(_002_[3]),
    .Q(bp[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _333_ (
    .CLK(clk),
    .D(_002_[4]),
    .Q(bp[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _334_ (
    .CLK(clk),
    .D(_002_[5]),
    .Q(bp[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _335_ (
    .CLK(clk),
    .D(_002_[6]),
    .Q(bp[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _336_ (
    .CLK(clk),
    .D(_002_[7]),
    .Q(bp[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _337_ (
    .CLK(clk),
    .D(_002_[8]),
    .Q(bp[8]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _338_ (
    .CLK(clk),
    .D(_002_[9]),
    .Q(bp[9]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _339_ (
    .CLK(clk),
    .D(_006_),
    .Q(sample),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _340_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(bn[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _341_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(bn[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _342_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(bn[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _343_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(bn[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _344_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(bn[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _345_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(bn[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _346_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(bn[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _347_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(bn[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _348_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(bn[8]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _349_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(bn[9]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _350_ (
    .CLK(clk),
    .D(_004_[0]),
    .Q(code[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _351_ (
    .CLK(clk),
    .D(_004_[1]),
    .Q(code[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _352_ (
    .CLK(clk),
    .D(_004_[2]),
    .Q(code[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _353_ (
    .CLK(clk),
    .D(_004_[3]),
    .Q(code[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _354_ (
    .CLK(clk),
    .D(_004_[4]),
    .Q(code[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _355_ (
    .CLK(clk),
    .D(_004_[5]),
    .Q(code[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _356_ (
    .CLK(clk),
    .D(_004_[6]),
    .Q(code[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _357_ (
    .CLK(clk),
    .D(_004_[7]),
    .Q(code[7]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _358_ (
    .CLK(clk),
    .D(_004_[8]),
    .Q(code[8]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _359_ (
    .CLK(clk),
    .D(_004_[9]),
    .Q(code[9]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _360_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(bit_idx[0]),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _361_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(bit_idx[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _362_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(bit_idx[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffsnq_1 _363_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(bit_idx[3]),
    .SETN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _364_ (
    .CLK(clk),
    .D(_005_[0]),
    .Q(count[0]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _365_ (
    .CLK(clk),
    .D(_005_[1]),
    .Q(count[1]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _366_ (
    .CLK(clk),
    .D(_005_[2]),
    .Q(count[2]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _367_ (
    .CLK(clk),
    .D(_005_[3]),
    .Q(count[3]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _368_ (
    .CLK(clk),
    .D(_005_[4]),
    .Q(count[4]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _369_ (
    .CLK(clk),
    .D(_005_[5]),
    .Q(count[5]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _370_ (
    .CLK(clk),
    .D(_005_[6]),
    .Q(count[6]),
    .RN(rst_n)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffrnq_1 _371_ (
    .CLK(clk),
    .D(_005_[7]),
    .Q(count[7]),
    .RN(rst_n)
  );
  assign cmp_p_gt_n = comp;
  assign state[1] = comp_clk;
endmodule

module sar_fsm_wrapper(clk, rst_n, start, comp, sample, comp_clk, busy, valid, bp9, bp8, bp7, bp6, bp5, bp4, bp3, bp2, bp1, bp0, bn9, bn8, bn7, bn6, bn5, bn4, bn3, bn2, bn1, bn0, code9, code8, code7, code6, code5, code4, code3, code2, code1, code0);
  wire [9:0] bn;
  output bn0;
  output bn1;
  output bn2;
  output bn3;
  output bn4;
  output bn5;
  output bn6;
  output bn7;
  output bn8;
  output bn9;
  wire [9:0] bp;
  output bp0;
  output bp1;
  output bp2;
  output bp3;
  output bp4;
  output bp5;
  output bp6;
  output bp7;
  output bp8;
  output bp9;
  output busy;
  input clk;
  wire [9:0] code;
  output code0;
  output code1;
  output code2;
  output code3;
  output code4;
  output code5;
  output code6;
  output code7;
  output code8;
  output code9;
  input comp;
  output comp_clk;
  input rst_n;
  output sample;
  input start;
  output valid;
  \$paramod\sar_logic\N=10\SAMPLE_CYCLES=4\DAC_SETTLE_CYCLES=3\INVERT_COMP=1'0  u_sar (
    .bn(bn),
    .bp(bp),
    .busy(busy),
    .clk(clk),
    .code(code),
    .comp(comp),
    .comp_clk(comp_clk),
    .rst_n(rst_n),
    .sample(sample),
    .start(start),
    .valid(valid)
  );
  assign bn0 = bn[0];
  assign bn1 = bn[1];
  assign bn2 = bn[2];
  assign bn3 = bn[3];
  assign bn4 = bn[4];
  assign bn5 = bn[5];
  assign bn6 = bn[6];
  assign bn7 = bn[7];
  assign bn8 = bn[8];
  assign bn9 = bn[9];
  assign bp0 = bp[0];
  assign bp1 = bp[1];
  assign bp2 = bp[2];
  assign bp3 = bp[3];
  assign bp4 = bp[4];
  assign bp5 = bp[5];
  assign bp6 = bp[6];
  assign bp7 = bp[7];
  assign bp8 = bp[8];
  assign bp9 = bp[9];
  assign code0 = code[0];
  assign code1 = code[1];
  assign code2 = code[2];
  assign code3 = code[3];
  assign code4 = code[4];
  assign code5 = code[5];
  assign code6 = code[6];
  assign code7 = code[7];
  assign code8 = code[8];
  assign code9 = code[9];
endmodule
